export const DEFAULT_SETTINGS = {
  KIMI_MEM_MODEL: 'claude-sonnet-5',
  KIMI_MEM_CONTEXT_OBSERVATIONS: '50',
  KIMI_MEM_WORKER_PORT: '37700',
  KIMI_MEM_WORKER_HOST: '127.0.0.1',

  KIMI_MEM_PROVIDER: 'claude',
  KIMI_MEM_GEMINI_API_KEY: '',
  KIMI_MEM_GEMINI_MODEL: 'gemini-flash-latest',
  KIMI_MEM_OPENROUTER_API_KEY: '',
  KIMI_MEM_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  KIMI_MEM_OPENROUTER_SITE_URL: '',
  KIMI_MEM_OPENROUTER_APP_NAME: 'kimi-mem',
  KIMI_MEM_GEMINI_RATE_LIMITING_ENABLED: 'true',

  KIMI_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  KIMI_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  KIMI_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  KIMI_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  KIMI_MEM_CONTEXT_FULL_COUNT: '0',
  KIMI_MEM_CONTEXT_FULL_FIELD: 'narrative',
  KIMI_MEM_CONTEXT_SESSION_COUNT: '10',

  KIMI_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  KIMI_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',
} as const;
